sudo: false

os:
  - osx
  - linux

#language: python

#addons:
#  apt:
#    packages:
#      - gfortran
#      - libatlas-dev
#      - libatlas-base-dev
#      - liblapack-dev

#cache:
#  directories:
#     - $HOME/download/
#     - $HOME/install/

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.3
  - PYTHON_VERSION=3.4
  - PYTHON_VERSION=3.5

before_install:
- wget https://github.com/mzwiessele/travis_scripts/raw/master/download_miniconda.sh
- wget https://github.com/mzwiessele/travis_scripts/raw/master/install_retry.sh
- source download_miniconda.sh
- echo $PATH
- echo $MINICONDA_INSTALL

install:
- source install_retry.sh
- pip install codecov
- python setup.py develop

script:
- coverage run travis_tests.py

after_success:
  - codecov

